version: 2
jobs:
  test-openjdk-8:
    docker:
    - image: circleci/clojure:openjdk-8-lein-2.8.1-browsers-legacy

    steps:
    - checkout
    - run: lein deps
    - run: lein with-profile dev:clj-1.9 test
    - run: lein with-profile dev:clj-1.9 cljs-nashorn-tests
    - run: lein with-profile dev:clj-1.9 cljs-phantom-tests

  test-openjdk-11:
    docker:
    - image: circleci/clojure:openjdk-11-lein-2.8.1-browsers-legacy

    steps:
    - checkout
    - run: lein deps
    - run: lein with-profile dev:clj-1.9 test
    - run: lein with-profile dev:clj-1.9 cljs-phantom-tests

workflows:
  version: 2
  test:
    jobs:
    - test-openjdk-8
    - test-openjdk-11
